services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: lunch_time_app
        volumes:
            - ./:/var/www/
        depends_on:
            - db
        networks:
            - lunch_time_network
    db:
        image: postgres:15
        container_name: lunch_time_db
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5440:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - lunch_time_network
    nginx:
        image: nginx:alpine
        container_name: lunch_time_nginx
        ports:
            - "99:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - lunch_time_network
    ngrok:
        image: ngrok/ngrok
        container_name: lunch_time_ngrok
        environment:
            - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
        command: "http nginx:80"
        ports:
            - "4040:4040"
        depends_on:
            - nginx
        networks:
            - lunch_time_network
volumes:
    pgdata:

networks:
    lunch_time_network:
